theme: jekyll-theme-minimal
title: Welcome to our website!
description: We are a diverse group of researchers working in the Molecular Lab at the Indian Ocean Marine Research Centre. Follow this website for research updates
